## Timesketch Helm Production Values
## Please use these values to override the default Timesketch values with recommended resources and replica counts for production installations
##
## @section Timesketch Frontend Configuration
##
frontend:
  ## @param frontend.podSecurityContext Holds pod-level security attributes and common frontend container settings
  ## Some fields are also present in container.securityContext. Field values of container.securityContext take precedence over field values of PodSecurityContext
  ## ref https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#podsecuritycontext-v1-core
  ## e.g.
  ## fsgroup: 2000
  ##
  podSecurityContext: {}
  ## @param frontend.securityContext Holds security configuration that will be applied to the frontend container
  ## Some fields are present in both SecurityContext and PodSecurityContext. When both are set, the values in SecurityContext take precedence
  ## ref https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#securitycontext-v1-core
  ## e.g.
  ## capabilities
  ##   drop:
  ##   - ALL
  ## readOnlyRootFilesystem: true
  ## runAsNonRoot: true
  ## runAsUser: 1000
  ##
  securityContext: {}
  ## Frontend resource requests and limits
  ## @param frontend.resources.requests.cpu Requested cpu for the frontend container
  ## @param frontend.resources.requests.memory Requested memory for the frontend container
  ## @param frontend.resources.limits.cpu Resource cpu limits for the frontend container
  ## @param frontend.resources.limits.memory Resource memory limits for the frontend container
  ##
  resources:
    requests:
      cpu: 2000m
      memory: 4000Mi
    limits:
      cpu: 8000m
      memory: 16000Mi
  ## @param frontend.nodeSelector Node labels for Timesketch frontend pods assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  ## @param frontend.tolerations Tolerations for Timesketch frontend pods assignment
  ## ref https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  ##
  tolerations: []
  ## @param frontend.affinity Affinity for Timesketch frontend pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}
## @section Timesketch Worker Configuration
##
worker:
  ## @param worker.podSecurityContext Holds pod-level security attributes and common worker container settings
  ## Some fields are also present in container.securityContext. Field values of container.securityContext take precedence over field values of PodSecurityContext
  ## ref https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#podsecuritycontext-v1-core
  ## e.g.
  ## fsgroup: 2000
  ##
  podSecurityContext: {}
  ## @param worker.securityContext Holds security configuration that will be applied to the worker container
  ## Some fields are present in both SecurityContext and PodSecurityContext. When both are set, the values in SecurityContext take precedence
  ## ref https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.27/#securitycontext-v1-core
  ## e.g.
  ## capabilities
  ##   drop:
  ##   - ALL
  ## readOnlyRootFilesystem: true
  ## runAsNonRoot: true
  ## runAsUser: 1000
  ##
  securityContext: {}
  ## Worker resource requests and limits
  ## @param worker.resources.requests.cpu Requested cpu for the worker container
  ## @param worker.resources.requests.memory Requested memory for the worker container
  ## @param worker.resources.limits.cpu Resource cpu limits for the worker container
  ## @param worker.resources.limits.memory Resource memory limits for the worker container
  ##
  resources:
    requests:
      cpu: 2000m
      memory: 4000Mi
    limits:
      cpu: 8000m
      memory: 16000Mi
  ## @param worker.nodeSelector Node labels for Timesketch worker pods assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
  ## @param worker.tolerations Tolerations for Timesketch worker pods assignment
  ## ref https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
  ##
  tolerations: []
  ## @param worker.affinity Affinity for Timesketch worker pods assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
  ##
  affinity: {}
## Persistence Storage Parameters
##
persistence:
  ## @param persistence.name Timesketch persistent volume name
  ##
  name: timesketchvolume
  ## @param persistence.size Timesketch persistent volume size
  ##
  size: 1T
  ## @param persistence.storageClass PVC Storage Class for Timesketch volume
  ## If default, storageClassName: <storageClass>, which enables GCP Filestore
  ##   when using the Filestore CSI Driver
  ##   ref https://cloud.google.com/kubernetes-engine/docs/how-to/persistent-volumes/filestore-csi-driver#access
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ## ref https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/#using-dynamic-provisioning
  ## 
  storageClass: standard-rwx
  ## @param persistence.accessModes PVC Access Mode for Timesketch volume
  ## Access mode may need to be updated based on the StorageClass
  ## ref https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes
  ## 
  accessModes:
    - ReadWriteMany
## @section Third Party Configuration
## This section contains all the main configuration for third party dependencies
## Timesketch requires to run
##
## @section Opensearch Configuration Parameters
## IMPORTANT: The Opensearch Security Plugin / TLS has not yet been configured by default
## ref on steps required https://opensearch.org/docs/1.1/security-plugin/configuration/index/
## To see a full list of available values, run helm show values charts/opensearch*
##
opensearch:
  ## @param opensearch.enabled Enables the Opensearch deployment
  ##
  enabled: true
  ## @param opensearch.replicas Number of Opensearch instances to deploy
  ##
  replicas: 3
  ## @param opensearch.sysctlInit.enabled Sets optimal sysctl's through privileged initContainer
  ##
  sysctlInit:
    enabled: true
  ## @param opensearch.opensearchJavaOpts Sets the size of the Opensearch Java heap
  ## It is recommended to use at least half the system's available ram
  ## 
  opensearchJavaOpts: "-Xms64g -Xmx64g"
  ## @param opensearch.httpPort Opensearch service port
  ##
  httpPort: 9200
  ## Opensearch persistence configuration
  ##
  persistence:
    ## @param opensearch.persistence.size Opensearch Persistent Volume size. A persistent volume would be created for each Opensearch replica running
    ##
    size: 1Ti
  ## Opensearch resource requests
  ## @param opensearch.resources.requests.cpu Requested cpu for the Opensearch containers
  ## @param opensearch.resources.requests.memory Requested memory for the Opensearch containers 
  ##
  resources:
    requests:
      cpu: 8000m
      memory: 32Gi
  ## @param opensearch.nodeSelector Node labels for Opensearch pods assignment
  ## ref: https://kubernetes.io/docs/user-guide/node-selection/
  ##
  nodeSelector: {}
## @section Redis Configuration Parameters
## IMPORTANT: Redis is deployed with Auth enabled by default
## To see a full list of available values, run helm show values charts/redis*
##
redis:
  ## @param redis.enabled Enables the Redis deployment
  ##
  enabled: true
  ## @param redis.sentinel.enabled Enables Redis Sentinel on Redis pods
  ## IMPORTANT: This has not been tested for Timesketch so would leave this disabled
  ##
  sentinel:
    enabled: false
  ## Master Redis Service configuration
  ##
  master:
    ## @param redis.master.count Number of Redis master instances to deploy (experimental, requires additional configuration)
    ##
    count: 1
    ## Redis master persistence configuration
    ##
    persistence:
      ## @param redis.master.persistence.size Redis master Persistent Volume size
      ##
      size: 500Gi
    ## Redis master resource requests and limits
    ## @param redis.master.resources.requests.cpu Requested cpu for the Redis master containers
    ## @param redis.master.resources.requests.memory Requested memory for the Redis master containers 
    ## @param redis.master.resources.limits.cpu Resource cpu limits for the Redis master containers
    ## @param redis.master.resources.limits.memory Resource memory limits for the Redis master containers
    ##
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 8000m
        memory: 16Gi
  ## Redis replicas configuration parameters
  ##
  replica:
    ## @param redis.replica.replicaCount Number of Redis replicas to deploy
    ##
    replicaCount: 3
    ## Redis replicas persistence configuration
    ##
    persistence:
      ## @param redis.replica.persistence.size Redis replica Persistent Volume size
      ##
      size: 500Gi
    ## Redis Replica resource requests and limits
    ## @param redis.replica.resources.requests.cpu Requested cpu for the Redis replica containers
    ## @param redis.replica.resources.requests.memory Requested memory for the Redis replica containers 
    ## @param redis.replica.resources.limits.cpu Resource cpu limits for the Redis replica containers
    ## @param redis.replica.resources.limits.memory Resource memory limits for the Redis replica containers
    ##
    resources:
      requests:
        cpu: 4000m
        memory: 8Gi
      limits:
        cpu: 8000m
        memory: 16Gi 
## @section Postgresql Configuration Parameters
## IMPORTANT: Postgresql is deployed with Auth enabled by default
## To see a full list of available values, run helm show values charts/postgresql*
##
postgresql:
  ## @param postgresql.enabled Enables the Postgresql deployment
  ##
  enabled: true
  ## PostgreSQL Primary configuration parameters
  ##
  primary:
    ## PostgreSQL Primary persistence configuration
    ##
    persistence:
      ## @param postgresql.primary.persistence.size PostgreSQL Persistent Volume size
      ##
      size: 500Gi
    ## PostgreSQL Primary resource requests and limits
    ## @param postgresql.primary.resources.requests.cpu Requested cpu for the PostgreSQL Primary containers
    ## @param postgresql.primary.resources.requests.memory Requested memory for the PostgreSQL Primary containers
    ## @param postgresql.primary.resources.limits Resource limits for the PostgreSQL Primary containers
    ##
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits: {}
  ## PostgreSQL read only replica parameters (only used when `architecture` is set to `replication`)
  ## 
  readReplicas:
    ## @param postgresql.readReplicas.replicaCount Number of PostgreSQL read only replicas
    ##
    replicaCount: 1
    ## PostgreSQL Persistent Storage configuration
    ##
    persistence:
      ## @param postgresql.readReplicas.persistence.size PostgreSQL Persistent Volume size
      ##
      size: 500Gi
    ## PostgreSQL read only resource requests and limits
    ## @param postgresql.readReplicas.resources.requests.cpu Requested cpu for the PostgreSQL read only containers
    ## @param postgresql.readReplicas.resources.requests.memory Requested memory for the PostgreSQL read only containers
    ## @param postgresql.readReplicas.resources.limits Resource limits for the PostgreSQL read only containers
    ##
    resources:
      requests:
        cpu: 250m
        memory: 256Mi
      limits: {}